#!/bin/sh
#
# Simulate an i3 scratchpad in BSPWM. Spawn terminal if the scratchpad is
# empty, if not toggle visibility.
# Requires bspwm, xdotool.
#
# use: /path/this.script <class_name> </path/cmd.sh>

if [ -z "$1" ]; then
    echo "Usage: $0 <name of hidden scratchpad window>"
    exit 1
fi

pids="$(xdotool search --classname "${1}")"
if [ -z "$pids" ]; then
    "${2}" &
    sleep 0.2
    pids=$(xdotool search --classname "${1}")
fi
for pid in $pids; do
    bspc node $pid --flag hidden -d focused -f
done

