#! /bin/bash      just for vscode highlighting

image/bmp;feh %s
image/gif;feh %s
image/ilbm;feh %s
image/jpg;feh %s
image/jpeg;feh %s
image/png;feh %s
image/tiff;feh %s
image/x-png;feh %s
image/x-ilbm;feh %s

application/pdf     ; /usr/bin/zathura %s                     ; copiousoutput

# text, html, xml
# text/plain;vim %s
# text/xml;vim %s
# text/x-diff;vim %s
text/html ; w3m -dump -T text/html '%s'; copiousoutput; description=HTML Text; nametemplate=%s.html
# text/html           ; w3m -dump -T text/html -cols 70         ; copiousoutput; description=HTML Text; test=type w3m >/dev/null
# text/htm            ; w3m -dump -T text/html -cols 70         ; copiousoutput; description=HTML Text; test=type w3m >/dev/null
# message/html        ; w3m -dump -T text/html -cols 70         ; copiousoutput; description=HTML Text; test=type w3m >/dev/null
# message/htm         ; w3m -dump -T text/html -cols 70         ; copiousoutput; description=HTML Text; test=type w3m >/dev/null

# miscellaneous file types can end up as this (md/markdown is one)
application/octet-stream;vim %s

# bound as <return> on attachments view in mutt
#text/html;xdg-open %s &; needsterminal;

# default command for mutt to use when viewing html emails w/ no text version
#text/html; surf %s; nametemplate=%s.html; copiousoutput;
# text/html; lynx -assume_charset=%{charset} -display_charset=utf-8 -dump %s; nametemplate=%s.html; copiousoutput
# text/html;w3m -I %{charset} -T text/html; copiousoutput;
#text/html;elinks -dump; copiousoutput;
#message/html;elinks -dump; copiousoutput;
#message/htm;elinks -dump; copiousoutput;

# pdf
application/pdf;zathura %s
image/pdf;zathura %s

# word, excel
# wordview is in the catdoc package
application/rtf;wordview %s
application/msword;wordview %s
#application/vnd.openxmlformats-officedocument.wordprocessingml.document;abiword %s # .docx
application/vnd.oasis.opendocument.text;abiword %s
application/excel;gnumeric %s; copiousoutput; nametemplate=%s.xls
application/msexcel;gnumeric %s; copiousoutput; nametemplate=%s.xls
application/vnd.ms-excel;gnumeric %s; copiousoutput; nametemplate=%s.xls
application/x-msexcel;gnumeric %s; copiousoutput; nametemplate=%s.xls

text/calendar; mutt-ics; copiousoutput
application/ics; mutt-ics; copiousoutput

# vim: fdm=marker
# vim: filetype=muttrc
