#!/usr/bin/env bash

# ================================================================================================================================
#
#                                                       NEW MESSAGES INFO
#
#                                                       Update: 2023.01.16
#
# ================================================================================================================================

#COUNT NEW MAIL FOR EVERY MAILDIR

MAILDIRNEW="$HOME/mail/bteb/INBOX/new/"
MAILDIRNEW1="$HOME/mail/live/Inbox/new/"

NEW="$(find $MAILDIRNEW -type f | wc -l)"
NEW1="$(find $MAILDIRNEW1 -type f | wc -l)"

if [ $NEW -gt 0 ] || [ $NEW1 -gt 0 ]; then
     # dunstify -r 7777 -a "neomutt" normal  "New mail! \n\nBTEB: $new   HOTMAIL: $new1"
     # dunstify -r 7777 -a "neomutt" -u c critical "New mail! \n\nBTEB: $new   HOTMAIL: $new1"
     powershell.exe -Command New-BurntToastNotification -Text "NewMail", "BTEB：$NEW",  "HOTMAIL：$NEW1"
fi
