#!/usr/bin/env bash

# ================================================================================================================================
#
#                                                             IFACE                                                          
#
#                                                       Update: 2023.01.16                                                      
#
# ================================================================================================================================

# USE THE PROVIDED INTERFACE, OTHERWISE THE DEVICE USED FOR THE DEFAULT ROUTE.
IF="${IFACE:-$BLOCK_INSTANCE}"
IF="${IF:-$(ip route | awk '/^default/ { print $5 ; exit }')}"

# EXIT IF THERE IS NO DEFAULT ROUTE
[[ -z "$IF" ]] && exit

#------------------------------------------------------------------------

# AS PER #36 -- IT IS TRANSPARENT: E.G. IF THE MACHINE HAS NO BATTERY OR WIRELESS
# CONNECTION (THINK DESKTOP), THE CORRESPONDING BLOCK SHOULD NOT BE DISPLAYED.
[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------

AF=${ADDRESS_FAMILY:-inet6?}
LABEL="${LABEL:-}"

for flag in "$1" "$2"; do
  case "$flag" in
    -4)
      AF=inet ;;
    -6)
      AF=inet6 ;;
    -L)
      if [[ "$IF" = "" ]]; then
        LABEL="iface "
      else
        LABEL="$IF: "
      fi ;;
  esac
done

if [[ "$IF" = "" ]] || [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo "${LABEL}down" # FULL TEXT
  echo "${LABEL}down" # SHORT TEXT
  echo \#FF0000       # COLOR
  exit
fi

# IF NO INTERFACE IS FOUND, USE THE FIRST DEVICE WITH A GLOBAL SCOPE
IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^ \/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

#------------------------------------------------------------------------

echo "$LABEL$IPADDR" # FULL TEXT
echo "$LABEL$IPADDR" # SHORT TEXT
