#!/usr/bin/env bash

# ================================================================================================================================
#
#                                                         STARTUP NEOMUTT                                                          
#
#                                                       Update: 2023.01.16                                                      
#
# ================================================================================================================================

DBM=$(wmctrl -l | grep -c "neomutt")
COLOR_ON="#E06C75"
COLOR_OFF="#ABB2BF"

case $BLOCK_BUTTON in
    1) # LEFT CLICK
        i3-msg --quiet "exec --no-startup-id raiseorlaunch -r -t neomutt -e '--no-startup-id alacritty -d 100 30 -t neomutt -e neomutt'"
        ;;
    2) # MIDDLE CLICK
        i3-msg "kill"
        ;;
    3) # RIGHT CLICK
        i3-msg "kill"
        ;;
esac

if [[ $DBM -eq 0 ]]; then
    echo "<span color='$COLOR_OFF'>  Neomutt</span>"
else
    echo "<span color='$COLOR_ON' >  Neomutt</span>"
fi

