#!/usr/bin/env bash

# ================================================================================================================================
#
#                                                         STARTUP NOTION                                                          
#
#                                                       Update: 2023.01.16                                                      
#
# ================================================================================================================================

DBM=$( xdotool search --classname notion.so)
COLOR_ON="#E06C75"
COLOR_OFF="#ABB2BF"

case $BLOCK_BUTTON in
    1) # LEFT CLICK
        i3-msg --quiet "exec --no-startup-id raiseorlaunch -r -c 'notion.so' -c 'Microsoft-edge' -e '--no-startup-id microsoft-edge -force-dark-mode --enable-features=OverlayScrollbar --enable-plugins --process-per-tab --app=https://notion.so'" > /dev/null
        ;;
    2) # MIDDLE CLICK
        i3-msg "kill"
        ;;
    3) # RIGHT CLICK
        i3-msg "kill"
        ;;
esac

if [[ $DBM -eq 0 ]]; then
    echo "<span color='$COLOR_off'>  Notion</span>"
else
    echo "<span color='$COLOR_on' >  Notion</span>"
fi

