#!/usr/bin/env bash

# ================================================================================================================================
#
#                                                           SCRATCHPAD                                                          
#
#                                                       Update: 2023.01.16                                                      
#
# ================================================================================================================================

SHOW_COUNT() {

  COUNT="$(i3-msg -t get_tree | jq '.' | grep -c '"scratchpad_state": "fresh"')"

  echo "${COUNT}"
  echo "${COUNT}"

  if   [[ "${COUNT}" -gt 5 ]]; then
    echo "#E06C75"
  elif [[ "${COUNT}" -gt 4 ]]; then
    echo "#C678DD"
  elif [[ "${COUNT}" -gt 3 ]]; then
    echo "#E5C07B"
  elif [[ "${COUNT}" -gt 2 ]]; then
    echo "#61AFEF"
  else
    echo "#ABB2BF"
  fi
}

case $BLOCK_BUTTON in
  1) i3-msg "SCRATCHPAD SHOW" 2>&1 >/dev/null;;
  3) i3-msg "SCRATCHPAD sHOW; floating toggle" 2>&1 >/dev/null
esac

SHOW_COUNT

