#!/usr/bin/env bash

# ================================================================================================================================
#
#                                                          STARTUP VIM
#
#                                                       Update: 2023.01.16                                                      
#
# ================================================================================================================================

DBM=$(wmctrl -l | grep -c "scratchpad")
COLOR_ON="#E06C75"
COLOR_OFF="#ABB2BF"

case $BLOCK_BUTTON in
    1) # LEFT CLICK
        i3-msg --quiet "exec --no-startup-id raiseorlaunch -r -t scratchpad -e '--no-startup-id alacritty -d 100 30 -t scratchpad -e vim $HOME/.scratchpad'"
        ;;
    2) # MIDDLE CLICK
        i3-msg --no-startup-id exec "kill"
        ;;
    3) # RIGHT CLICK
        i3-msg --no-startup-id exec "kill"
        ;;
esac

if [[ $DBM -eq 0 ]]; then
    echo "<span color='$COLOR_OFF'>  Vim</span>"
else
    echo "<span color='$COLOR_ON' >  Vim</span>"
fi

